[build]
command = "node fetch-content.js && hugo -b https://docs.spatie.be"
publish = "public"

[context.production.environment]
HUGO_VERSION = "0.55.5"
HUGO_ENV = "production"

[[redirects]]
  from = "https://docs-spatie.netlify.com/*"
  to = "https://docs.spatie.be/:splat"
  status = 301
